
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.Action stopAction;
	
	private global::Gtk.Action stopAction1;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.MenuBar menubar2;
	
	private global::Gtk.Entry txtInput;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView txtOutput;
	
	private global::Gtk.Button cmdDecrypt;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.EventBox eventbox2;
	
	private global::Gtk.DrawingArea drawingarea2;
	
	private global::Gtk.Image image1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.stopAction = new global::Gtk.Action ("stopAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-stop");
		this.stopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.stopAction, null);
		this.stopAction1 = new global::Gtk.Action ("stopAction1", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-stop");
		this.stopAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.stopAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='stopAction1' action='stopAction1'/></menu><menu name='AboutAction' action='AboutAction'/></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.fixed1.Add (this.menubar2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.menubar2]));
		w2.X = -1;
		w2.Y = 3;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtInput = new global::Gtk.Entry ();
		this.txtInput.CanFocus = true;
		this.txtInput.Name = "txtInput";
		this.txtInput.IsEditable = true;
		this.txtInput.InvisibleChar = '•';
		this.fixed1.Add (this.txtInput);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtInput]));
		w3.X = 298;
		w3.Y = 125;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtOutput = new global::Gtk.TextView ();
		this.txtOutput.WidthRequest = 200;
		this.txtOutput.HeightRequest = 50;
		this.txtOutput.CanFocus = true;
		this.txtOutput.Name = "txtOutput";
		this.txtOutput.Overwrite = true;
		this.GtkScrolledWindow.Add (this.txtOutput);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w5.X = 510;
		w5.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.cmdDecrypt = new global::Gtk.Button ();
		this.cmdDecrypt.CanFocus = true;
		this.cmdDecrypt.Name = "cmdDecrypt";
		this.cmdDecrypt.UseUnderline = true;
		this.cmdDecrypt.Label = global::Mono.Unix.Catalog.GetString ("Decrypt");
		this.fixed1.Add (this.cmdDecrypt);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.cmdDecrypt]));
		w6.X = 320;
		w6.Y = 497;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.WidthRequest = 500;
		this.label3.HeightRequest = 200;
		this.label3.Name = "label3";
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w7.X = 328;
		w7.Y = 301;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.eventbox2 = new global::Gtk.EventBox ();
		this.eventbox2.WidthRequest = 300;
		this.eventbox2.HeightRequest = 300;
		this.eventbox2.Name = "eventbox2";
		// Container child eventbox2.Gtk.Container+ContainerChild
		this.drawingarea2 = new global::Gtk.DrawingArea ();
		this.drawingarea2.Name = "drawingarea2";
		this.eventbox2.Add (this.drawingarea2);
		this.fixed1.Add (this.eventbox2);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.eventbox2]));
		w9.X = 711;
		w9.Y = 327;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image ();
		this.image1.WidthRequest = 400;
		this.image1.HeightRequest = 400;
		this.image1.Name = "image1";
		this.fixed1.Add (this.image1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.image1]));
		w10.X = 1083;
		w10.Y = 168;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 4328;
		this.DefaultHeight = 801;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.stopAction1.Activated += new global::System.EventHandler (this.OnClick);
		this.fixed1.Shown += new global::System.EventHandler (this.onShown);
		this.cmdDecrypt.Clicked += new global::System.EventHandler (this.OnCmdDecryptEntered);
	}
}
