
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed3;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Button cmdDecrypt;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView txtOutput;
	
	private global::Gtk.Entry txtInput;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Image image1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Barcode Value");
		this.fixed3.Add (this.label4);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label4]));
		w1.X = 106;
		w1.Y = 74;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Decrypted value");
		this.fixed3.Add (this.label5);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label5]));
		w2.X = 96;
		w2.Y = 113;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.cmdDecrypt = new global::Gtk.Button ();
		this.cmdDecrypt.CanFocus = true;
		this.cmdDecrypt.Name = "cmdDecrypt";
		this.cmdDecrypt.UseUnderline = true;
		this.cmdDecrypt.Label = global::Mono.Unix.Catalog.GetString ("Decrypt");
		this.fixed3.Add (this.cmdDecrypt);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.cmdDecrypt]));
		w3.X = 619;
		w3.Y = 292;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtOutput = new global::Gtk.TextView ();
		this.txtOutput.WidthRequest = 382;
		this.txtOutput.HeightRequest = 186;
		this.txtOutput.CanFocus = true;
		this.txtOutput.Name = "txtOutput";
		this.GtkScrolledWindow.Add (this.txtOutput);
		this.fixed3.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.GtkScrolledWindow]));
		w5.X = 203;
		w5.Y = 118;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.txtInput = new global::Gtk.Entry ();
		this.txtInput.WidthRequest = 416;
		this.txtInput.HeightRequest = 0;
		this.txtInput.CanFocus = true;
		this.txtInput.Name = "txtInput";
		this.txtInput.IsEditable = true;
		this.txtInput.InvisibleChar = '●';
		this.fixed3.Add (this.txtInput);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.txtInput]));
		w6.X = 192;
		w6.Y = 71;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.WidthRequest = 302;
		this.label3.HeightRequest = 149;
		this.label3.Name = "label3";
		this.fixed3.Add (this.label3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label3]));
		w7.X = 397;
		w7.Y = 366;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image ();
		this.image1.WidthRequest = 271;
		this.image1.HeightRequest = 157;
		this.image1.Name = "image1";
		this.fixed3.Add (this.image1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.image1]));
		w8.X = 130;
		w8.Y = 383;
		this.Add (this.fixed3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 745;
		this.DefaultHeight = 570;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.cmdDecrypt.Clicked += new global::System.EventHandler (this.OnCmdDecryptEntered);
	}
}
